#ifndef ENUM_HPP
#define ENUM_HPP

enum eStatusCode {
  PARSING_COMPLETED = 0,
  PARSING_INCOMPLETED = 1,
  PARSING_ERROR = 2,
  RESPONSE_INCOMPLETED = 3,
  SOCKET_READ_ERROR = 4,
  SOCKET_DISCONNECTED = 5,
  READ_OK = 6,
  ERROR = 7,
  REDIRECT = 8,
  PRIORITY_HEADER_OK = 9,
  PATH_INACCESSIBLE = 10,
  PATH_IS_DIRECTORY = 11,
  PATH_IS_FILE = 12,
  PATH_UNKNOWN = 13,
  FILE_CREATE = 14,
  FILE_APPEND = 15,
  PATH_NOT_FOUND = 17,
  INFORMATIONAL_CONTINUE = 100,
  INFORMATIONAL_SWITCHING_PROTOCOLS = 101,
  SUCCESSFUL_OK = 200,
  SUCCESSFUL_CREATERD = 201,
  SUCCESSFUL_ACCEPTED = 202,
  SUCCESSFUL_NON_AUTHORITATIVE_INFORMATION = 203,
  SUCCESSFUL_NO_CONTENT = 204,
  SUCCESSFUL_RESET_CONTENT = 205,
  SUCCESSFUL_PARTIAL_CONTENT = 206,
  REDIRECTION_MULTIPLE_CHOICES = 300,
  REDIRECTION_MOVED_PERMANENTLY = 301,
  REDIRECTION_FOUND = 302,
  REDIRECTION_SEE_OTHER = 303,
  REDIRECTION_NOT_MODIFIED = 304,
  REDIRECTION_USE_PROXY = 305,
  REDIRECTION_UNUSED = 306,
  REDIRECTION_TEMPORARY_REDIRECT = 307,
  REDIRECTION_PERMANENT_REDIRECT = 308,
  CLIENT_ERROR_BAD_REQUEST = 400,
  CLIENT_ERROR_UNAUTHORIZED = 401,
  CLIENT_ERROR_PAYMENT_REQUIRED = 402,
  CLIENT_ERROR_FORBIDDEN = 403,
  CLIENT_ERROR_NOT_FOUND = 404,
  CLIENT_ERROR_METHOD_NOT_ALLOWED = 405,
  CLIENT_ERROR_NOT_ACCEPTABLE = 406,
  CLIENT_ERROR_PROXY_AUTHENTICATION_REQUIRED = 407,
  CLIENT_ERROR_REQUEST_TIMEOUT = 408,
  CLIENT_ERROR_CONFLICT = 409,
  CLIENT_ERROR_GONE = 410,
  CLIENT_ERROR_LENGTH_REQUIRED = 411,
  CLIENT_ERROR_PRECONDITION_FAILED = 412,
  CLIENT_ERROR_CONTENT_TOO_LARGE = 413,
  CLIENT_ERROR_URI_TOO_LONG = 414,
  CLIENT_ERROR_UNSUPPORTED_MEDIA_TYPE = 415,
  CLIENT_ERROR_RANGE_NOT_SATISFIABLE = 416,
  CLIENT_ERROR_EXPECTATION_FAILED = 417,
  CLIENT_ERROR_UNUSED = 418,
  CLIENT_ERROR_MISDIRECTED_REQUEST = 421,
  CLIENT_ERROR_UNPROCESSABLE_CONTENT = 422,
  CLIENT_ERROR_UPGRADE_REQUIRED = 426,
  SERVER_ERROR_INTERNAL_SERVER_ERROR = 500,
  SERVER_ERROR_NOT_IMPLEMENTED = 501,
  SERVER_ERROR_BAD_GATEWAY = 502,
  SERVER_SERVICE_UNAVAILABLE = 503,
  SERVER_ERROR_GATEWAY_TIMEOUT = 504,
  SERVER_ERROR_HTTP_VERSION_NOT_SUPPORTED = 505
};

enum eState {
  RequestMethodStart,
  RequestMethod,
  RequestUriStart,
  RequestUri,
  RequestHttpVersion_h,
  RequestHttpVersion_ht,
  RequestHttpVersion_htt,
  RequestHttpVersion_http,
  RequestHttpVersion_slash,
  RequestHttpVersion_majorStart,
  RequestHttpVersion_major,
  RequestHttpVersion_minorStart,
  RequestHttpVersion_minor,

  ResponseStatusStart,
  ResponseHttpVersion_ht,
  ResponseHttpVersion_htt,
  ResponseHttpVersion_http,
  ResponseHttpVersion_slash,
  ResponseHttpVersion_majorStart,
  ResponseHttpVersion_major,
  ResponseHttpVersion_minorStart,
  ResponseHttpVersion_minor,
  ResponseHttpVersion_spaceAfterVersion,
  ResponseHttpVersion_statusCode,
  ResponseHttpVersion_statusCodeStart,
  ResponseHttpVersion_spaceAfterStatusCode,
  ResponseHttpVersion_statusText,
  ResponseHttpVersion_statusTextStart,
  ResponseHttpVersion_newLine,

  HeaderLineStart,
  HeaderLws,
  HeaderName,
  SpaceBeforeHeaderValue,
  HeaderValue,
  ExpectingNewline_2,
  ExpectingNewline_3,

  Post,
  ChunkSize,
  ChunkExtensionName,
  ChunkExtensionValue,
  ChunkSizeNewLine,
  ChunkSizeNewLine_2,
  ChunkSizeNewLine_3,
  ChunkTrailerName,
  ChunkTrailerValue,

  ChunkDataNewLine_1,
  ChunkDataNewLine_2,
  ChunkData,
};

#endif